# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import shop.modifiers.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0002_auto_20151016_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Discount code')),
            ],
            options={
                'verbose_name': 'Cart discount code',
                'verbose_name_plural': 'Cart discount codes',
            },
        ),
        migrations.CreateModel(
            name='DiscountBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Is discount valid only with included code', max_length=30, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now, verbose_name='Valid from')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid until')),
                ('num_uses', models.IntegerField(default=0, verbose_name='Number of times already used')),
            ],
            options={
                'ordering': [],
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
            bases=(models.Model, shop.modifiers.base.BaseCartModifier),
        ),
        migrations.AddField(
            model_name='discountbase',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_discount.discountbase_set+', to='contenttypes.ContentType'),
        ),
        #migrations.AddField(
            #model_name='cartdiscountcode',
            #name='cart',
            #field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BaseCart'),
        #),
    ]
